version: "2.1"

volumes:
  weights: {}
  data-db: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.8.1@sha256:2545e3d1efe793510e276476de662fffa4e7db0b01a6a18ddf8d68a20f08220c
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/
