version: "2.1"

volumes:
  weights: {}
  data-db: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.5.1@sha256:ee58a0ded773540c7ddae8866c658d9ff4fbc6fdc49b22fb1fe86963622839e3
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/
