version: "2.1"

volumes:
  weights: {}
  data-db: {}
  tailscale: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.3.2@sha256:d5f078e48e17e8017af1f423742836bc68abde1bfb8bbbefe79656ffb01e0d08
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/

  tailscale:
    build: tailscale
    network_mode: host
    restart: on-failure
    volumes:
      - tailscale:/var/lib/tailscale
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/
