version: "2.1"

volumes:
  weights: {}
  data-db: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.5.0@sha256:577b31c61d5408d4c04d28ba7dc39483030871b2ab430c18afb5ab9a8271663e
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/
