version: "2.1"

volumes:
  weights: {}
  data-db: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.4.1@sha256:3875d5ba45ab7864f0833c29de57899742ab6408090afd6da204a6000d709f50
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/
