version: "2.1"

volumes:
  weights: {}
  data-db: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.8.2@sha256:b6a0a6f044c3b64e1cdb193c3f2a843686ee44b232c786dac792a7afe7e0b27b
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/
