version: "2.1"

volumes:
  weights: {}
  data-db: {}

services:
  serge:
    image: ghcr.io/serge-chat/serge:0.3.2@sha256:6deb72470fd1ec7717eaeba631a0cd8f98c7004a10e4ee657fca8b2414341cf2
    ports:
      - 80:8008/tcp
    volumes:
      - weights:/usr/src/app/weights
      - data-db:/data/db/
